### ISSUE TITLE
The relex docker image doesn't run on ARM

### ISSUE THREAD

**Issue by Kidist-Abraham** [opencog/TinyCog#18]
Is there any other way to run the server on rpi? or should we make an image which runs on ARM?

**Comment by Dagiopia** [comment]
We shouldn't use docker on the pi. But running the relex server needs a couple of changes. One, when installing with the script, it sets the java path to the openjdk path which would be wrong on the pi because it's best to use the oracle jdk/jvm package not the openjdk one since the former has 20 times better performance and the other change is when staring the server. The opencog-server.sh script sets the heap size a wildely

**Comment by Dagiopia** [comment]
Didn't mean to close the issue. My device has a habit of touching itself :)

**Comment by Kidist-Abraham** [comment]
@Dagiopia we should only change this right? VM_OPTS="-Xmx256m"

**Comment by Dagiopia** [comment]
Yes, it's not Mich but it's all the pi got.

**Comment by linas** [comment]
Maybe you can set `VM_OPTS` smaller, too. No one knows how small you can make it, before it stops working.

**Comment by Dagiopia** [comment]
Hehe I know it's wrong but we got no choice here. It's not something that's suppose to run on something so small. We shall find out soon.
